// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeTutorial1.Data;

namespace PracticeTutorial1.Migrations
{
    [DbContext(typeof(ToturialDBContext))]
    [Migration("20210412092359_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeTutorial1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batch");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Batch = "23713", Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Skin 18+", Price = 492000m },
                        new { Id = 2, Batch = "LP9872", Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Pro Sunwhite", Price = 1350000m },
                        new { Id = 3, Batch = "46723", Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Manuka Gel 50ml", Price = 700000m }
                    );
                });

            modelBuilder.Entity("PracticeTutorial1.Models.UserLogin", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("User");

                    b.Property<string>("Vip");

                    b.HasKey("ID");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new { ID = "1", Password = "123456", User = "haovippro" },
                        new { ID = "2", Password = "123456", User = "langtucodon" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
